services:
  - type: web
    name: cripto_curr
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 manage.py runserver 0.0.0.0:8000
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
      - key: PORT
        value: "8000"
      - key: WEB_CONCURRENCY
        value: "1"
      - key: GUNICORN_CMD_ARGS
        value: "--workers=1 --threads=2 --timeout 120"