# Generated by Django 5.1.6 on 2025-02-19 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название токена')),
                ('symbol', models.CharField(max_length=10, unique=True, verbose_name='Символ')),
            ],
            options={
                'verbose_name': 'Токен',
                'verbose_name_plural': 'Токены',
            },
        ),
        migrations.CreateModel(
            name='CoinPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('price', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Цена USD')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='crypto_coins.token', verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Цена токена',
                'verbose_name_plural': 'Цены токенов',
                'ordering': ['-timestamp'],
            },
        ),
    ]
