# Generated by Django 5.1.6 on 2025-02-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_coins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='url_token',
            field=models.URLField(blank=True, default=None, null=True, unique=True, verbose_name='url адрес'),
        ),
    ]
